name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Optional: Generate lock file if needed
    - name: Restore dependencies
      run: dotnet restore src/ChartCareMVC/ChartCareMVC.sln --use-lock-file

    - name: Build
      run: dotnet build src/ChartCareMVC/ChartCareMVC.sln --no-restore

    - name: Test
      run: dotnet test src/ChartCareMVC/MVC-Tests/MVC-Tests.csproj --no-build --verbosity normal
